# fly.toml app configuration file generated for empty-grass-3146 on 2024-08-09T19:37:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-grass-3146"
primary_region = "arn"

[env]
  PORT = "3000"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
